### ISSUE TITLE
Unknown CMake command "configure_package_config_file"

### ISSUE THREAD

**Issue by star-hengxing** [ph3at/libenvpp#11]
Build fails:
```console
CMake Error at CMakeLists.txt:163 (configure_package_config_file):
  Unknown CMake command "configure_package_config_file".
```

CMakeLists.txt is missing `include(CMakePackageConfigHelpers)` that provides this macro.

**Comment by BlackMark29A** [comment]
I cannot reproduce this problem on my end. I guess this include somehow happens transitively or is included by default in my cmake setup.

Can you test whether PR #12 fixes this for you?

**Comment by star-hengxing** [comment]
Thanks, it work for me.
