### ISSUE TITLE
Exception in windows when variables with empty value 

### ISSUE THREAD

**Issue by karnotxo** [ph3at/libenvpp#7]
Detected in libenvpp 1.30 and 1.40
Running in windows 11, with msvc 2019, debug mode. 
In libenvpp_environment_windows.cpp, method `get_environment()` [line 42], when an empty variable is found:

> var_name_value: 
>  [0]: L"VSCODE_L10N_BUNDLE_LOCATION"
>  [1]: L""

In statement [line 62]:
` env_map[*convert_string(var_name_value[0])] = *convert_string(var_name_value[1]);`
an exception is thrown, because `std::optional` returned from second `convert_string` is empty:
  ```
#if _CONTAINER_DEBUG_LEVEL > 0
          _STL_VERIFY(this->_Has_value, "Cannot access value of empty optional");
  #endif // _CONTAINER_DEBUG_LEVEL > 0

```
Maybe it should return an `std::optional` containing an empty `std::string`  in this case

![image](https://github.com/ph3at/libenvpp/assets/57320535/bc5f08f1-1ea0-46bc-8dd6-11c3f474631a)

![image](https://github.com/ph3at/libenvpp/assets/57320535/c1e4a0d3-5a81-4d3f-a9e5-dda928426109)

**Comment by BlackMark29A** [comment]
Thanks for reporting this! I pushed a fix for this to the main branch, that will be included in the next release.
